spring:
  datasource:
    url: jdbc:mysql:///leyou?autoReconnect=true&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: root
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 1000
      test-on-borrow: true
  jpa:
    #show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
